### ISSUE TITLE
FIX - UnicodeDecodeError

### ISSUE THREAD

**Issue by AhmadMutiry** [1337r00t/TrendCatch#1]
بيئة العمل :
macOS v10.14.4
Default Terminal v2.9.4 
Python v2.7.16

رسالة الخطأ :
`
File "TrendCatch.py", line 70, in <module>
    search = trend(hashtag, cursor, X_Token, X_Secret)
  File "TrendCatch.py", line 18, in trend
.....
.....
UnicodeDecodeError: 'ascii' codec can't decode byte 0xd8 in position 1: ordinal not in range(128)
`

اصلاح الخطأ :

```
hashtag_utf8 = unicode(hashtag, "utf-8")

search = trend(hashtag_utf8, cursor, X_Token, X_Secret)
```

**Comment by abdoxfox** [comment]
Can be fixed also with
Search=trend(hashtag.encode('utf-8'), cursor, X_Token, X_Secret)

**Comment by AhmadMutiry** [comment]
جربتها من قبل لا يتم تنفيذ الكود مع نفس رسالة الخطأ!!

التعديل على ترميز المدخل للمتغير
hashtag
في السطر رقم ٥٠

**Comment by 1337r00t** [comment]
Thanks Ahmed | شكرا أحمد

Can you confirm the fix if it works or not ? | تقدر تأكد لي اذا تم اصلاح المشكلة او لا ؟

**Comment by AhmadMutiry** [comment]
العفو عزيزي

نعم الان يعمل
👍
